version: "3"
services:
  redis:
    image: redis:alpine
    ports:
      - "6379"
  db:
    image: postgres:9.4
    ports:
      - "5432"
    volumes:
      - db-data:/var/lib/postgresql/data
  vote:
    image: dockersamples/examplevotingapp_vote:before
    ports:
      - 5000:80
    depends_on:
      - redis
  result:
    image: dockersamples/examplevotingapp_result:before
    ports:
      - 5001:80
    depends_on:
      - db
  worker:
    image: dockersamples/examplevotingapp_worker
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    stop_grace_period: 1m30s
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
volumes:
  db-data:
